set_property SRC_FILE_INFO {cfile:C:/Users/deeps/project_4_part_2/project_4_part_2.srcs/constrs_1/imports/Lab_3_part_3/Basys3_Master.xdc rfile:../../../project_4_part_2.srcs/constrs_1/imports/Lab_3_part_3/Basys3_Master.xdc id:1} [current_design]
set_property src_info {type:XDC file:1 line:2 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN W5 [get_ports clk]
set_property src_info {type:XDC file:1 line:7 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN V17 [get_ports {signal}]
set_property src_info {type:XDC file:1 line:11 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN U16 [get_ports {outedge}]
set_property src_info {type:XDC file:1 line:15 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN U18 [get_ports reset]
